name: Dart CI

on:
  push:
    branches: [ production ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Build APK
      run: flutter build apk
